name: Auto Commit

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Memberikan izin menulis ke repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Buat perubahan
        run: |
          echo "Auto commit pada $(date)" >> auto_commit_log.txt
          git add .
          git commit -m "Auto commit: $(date)" || echo "No changes for commit"
          git push
